package com.sf.jfinal.qs.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("crm_goods_platform_order", "id", CrmGoodsPlatformOrder.class);
		arp.addMapping("crm_site", "id", CrmSite.class);
		arp.addMapping("sys_user", "id", User.class);
		arp.addMapping("crm_non_serviceman", "id", CrmNonServiceman.class);
		arp.addMapping("crm_goods_platform", "id", CrmGoodsPlatform.class);
		arp.addMapping("crm_goods_siteself", "id", CrmGoodsSiteself.class);
		arp.addMapping("crm_goods_siteself_order", "id", CrmGoodsSiteselfOrder.class);
		arp.addMapping("crm_gift_pack", "id", CrmGiftPack.class);
		arp.addMapping("sys_dict", "id", Dict.class);
		arp.addMapping("crm_goods_platform_transfer_order", "id", CrmGoodsPlatformTransferOrder.class);
	}
}
