package com.sf.jfinal.qs.model;

import com.sf.jfinal.qs.model.base.BaseCrmGoodsPlatformOrder;

import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CrmGoodsPlatformOrder extends BaseCrmGoodsPlatformOrder<CrmGoodsPlatformOrder> {

    public static final CrmGoodsPlatformOrder dao = new CrmGoodsPlatformOrder();

    public CrmGoodsPlatformOrder findByTradeNo(String tradeNo) {
        return dao.findFirst("select * from crm_goods_platform_order where trade_no=? limit 1", tradeNo);
    }

    public List<CrmGoodsPlatformOrder> findAllByTradeNo(String tradeNo) {
        return dao.find("select * from crm_goods_platform_order where trade_no=? ", tradeNo);
    }
}
