package com.sf.jfinal.qs.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCrmSite<M extends BaseCrmSite<M>> extends Model<M> implements IBean {

	public void setId(String id) {
		set("id", id);
	}

	public String getId() {
		return get("id");
	}

	public void setUserId(String userId) {
		set("user_id", userId);
	}

	public String getUserId() {
		return get("user_id");
	}

	public void setNumber(String number) {
		set("number", number);
	}

	public String getNumber() {
		return get("number");
	}

	public void setName(String name) {
		set("name", name);
	}

	public String getName() {
		return get("name");
	}

	public void setContacts(String contacts) {
		set("contacts", contacts);
	}

	public String getContacts() {
		return get("contacts");
	}

	public void setCorporator(String corporator) {
		set("corporator", corporator);
	}

	public String getCorporator() {
		return get("corporator");
	}

	public void setEmail(String email) {
		set("email", email);
	}

	public String getEmail() {
		return get("email");
	}

	public void setProvince(String province) {
		set("province", province);
	}

	public String getProvince() {
		return get("province");
	}

	public void setCity(String city) {
		set("city", city);
	}

	public String getCity() {
		return get("city");
	}

	public void setArea(String area) {
		set("area", area);
	}

	public String getArea() {
		return get("area");
	}

	public void setAddress(String address) {
		set("address", address);
	}

	public String getAddress() {
		return get("address");
	}

	public void setLnglat(String lnglat) {
		set("lnglat", lnglat);
	}

	public String getLnglat() {
		return get("lnglat");
	}

	public void setCategory(String category) {
		set("category", category);
	}

	public String getCategory() {
		return get("category");
	}

	public void setMobile(String mobile) {
		set("mobile", mobile);
	}

	public String getMobile() {
		return get("mobile");
	}

	public void setTelephone(String telephone) {
		set("telephone", telephone);
	}

	public String getTelephone() {
		return get("telephone");
	}

	public void setLicenseNumber(String licenseNumber) {
		set("license_number", licenseNumber);
	}

	public String getLicenseNumber() {
		return get("license_number");
	}

	public void setLicenseImg(String licenseImg) {
		set("license_img", licenseImg);
	}

	public String getLicenseImg() {
		return get("license_img");
	}

	public void setStatus(String status) {
		set("status", status);
	}

	public String getStatus() {
		return get("status");
	}

	public void setCheckFlag(String checkFlag) {
		set("check_flag", checkFlag);
	}

	public String getCheckFlag() {
		return get("check_flag");
	}

	public void setRemarks(String remarks) {
		set("remarks", remarks);
	}

	public String getRemarks() {
		return get("remarks");
	}

	public void setCreateBy(String createBy) {
		set("create_by", createBy);
	}

	public String getCreateBy() {
		return get("create_by");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}

	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

	public void setAreaManagerId(String areaManagerId) {
		set("area_manager_id", areaManagerId);
	}

	public String getAreaManagerId() {
		return get("area_manager_id");
	}

	public void setDueTime(java.util.Date dueTime) {
		set("due_time", dueTime);
	}

	public java.util.Date getDueTime() {
		return get("due_time");
	}

	public void setShareCode(String shareCode) {
		set("share_code", shareCode);
	}

	public String getShareCode() {
		return get("share_code");
	}

	public void setShareCodeSiteParentId(String shareCodeSiteParentId) {
		set("share_code_site_parent_id", shareCodeSiteParentId);
	}

	public String getShareCodeSiteParentId() {
		return get("share_code_site_parent_id");
	}

	public void setLevel(String level) {
		set("level", level);
	}

	public String getLevel() {
		return get("level");
	}

	public void setSmsAvailableAmount(Integer smsAvailableAmount) {
		set("sms_available_amount", smsAvailableAmount);
	}

	public Integer getSmsAvailableAmount() {
		return get("sms_available_amount");
	}

}
