package com.sf.jfinal.qs.model;

import com.sf.jfinal.qs.model.base.BaseDict;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Dict extends BaseDict<Dict> {
	public static final Dict dao = new Dict();
}
