package com.sf.jfinal.qs.model;

import com.sf.jfinal.qs.model.base.BaseCrmNonServiceman;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CrmNonServiceman extends BaseCrmNonServiceman<CrmNonServiceman> {
    public static final CrmNonServiceman dao = new CrmNonServiceman();
}
