package com.sf.jfinal.qs.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCrmGoodsPlatform<M extends BaseCrmGoodsPlatform<M>> extends Model<M> implements IBean {

	public void setId(String id) {
		set("id", id);
	}

	public String getId() {
		return get("id");
	}

	public void setSortNum(Integer sortNum) {
		set("sort_num", sortNum);
	}

	public Integer getSortNum() {
		return get("sort_num");
	}

	public void setNumber(String number) {
		set("number", number);
	}

	public String getNumber() {
		return get("number");
	}

	public void setName(String name) {
		set("name", name);
	}

	public String getName() {
		return get("name");
	}

	public void setBrand(String brand) {
		set("brand", brand);
	}

	public String getBrand() {
		return get("brand");
	}

	public void setModel(String model) {
		set("model", model);
	}

	public String getModel() {
		return get("model");
	}

	public void setCategory(String category) {
		set("category", category);
	}

	public String getCategory() {
		return get("category");
	}

	public void setUnit(String unit) {
		set("unit", unit);
	}

	public String getUnit() {
		return get("unit");
	}

	public void setUnitType(String unitType) {
		set("unit_type", unitType);
	}

	public String getUnitType() {
		return get("unit_type");
	}

	public void setDescription(String description) {
		set("description", description);
	}

	public String getDescription() {
		return get("description");
	}

	public void setIcon(String icon) {
		set("icon", icon);
	}

	public String getIcon() {
		return get("icon");
	}

	public void setImgs(String imgs) {
		set("imgs", imgs);
	}

	public String getImgs() {
		return get("imgs");
	}

	public void setSitePrice(java.math.BigDecimal sitePrice) {
		set("site_price", sitePrice);
	}

	public java.math.BigDecimal getSitePrice() {
		return get("site_price");
	}

	public void setPlatformPrice(java.math.BigDecimal platformPrice) {
		set("platform_price", platformPrice);
	}

	public java.math.BigDecimal getPlatformPrice() {
		return get("platform_price");
	}

	public void setProfit(java.math.BigDecimal profit) {
		set("profit", profit);
	}

	public java.math.BigDecimal getProfit() {
		return get("profit");
	}

	public void setSellFlag(String sellFlag) {
		set("sell_flag", sellFlag);
	}

	public String getSellFlag() {
		return get("sell_flag");
	}

	public void setType(String type) {
		set("type", type);
	}

	public String getType() {
		return get("type");
	}

	public void setDistributionType(String distributionType) {
		set("distribution_type", distributionType);
	}

	public String getDistributionType() {
		return get("distribution_type");
	}

	public void setStocks(java.math.BigDecimal stocks) {
		set("stocks", stocks);
	}

	public java.math.BigDecimal getStocks() {
		return get("stocks");
	}

	public void setSales(java.math.BigDecimal sales) {
		set("sales", sales);
	}

	public java.math.BigDecimal getSales() {
		return get("sales");
	}

	public void setStatus(String status) {
		set("status", status);
	}

	public String getStatus() {
		return get("status");
	}

}
