package com.sf.jfinal.qs.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCrmGiftPack<M extends BaseCrmGiftPack<M>> extends Model<M> implements IBean {

	public void setId(String id) {
		set("id", id);
	}

	public String getId() {
		return get("id");
	}

	public void setName(String name) {
		set("name", name);
	}

	public String getName() {
		return get("name");
	}

	public void setDescription(String description) {
		set("description", description);
	}

	public String getDescription() {
		return get("description");
	}

	public void setIdc(String idc) {
		set("idc", idc);
	}

	public String getIdc() {
		return get("idc");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setTakeTime(java.util.Date takeTime) {
		set("take_time", takeTime);
	}

	public java.util.Date getTakeTime() {
		return get("take_time");
	}

	public void setTakeBy(String takeBy) {
		set("take_by", takeBy);
	}

	public String getTakeBy() {
		return get("take_by");
	}

	public void setTakeSiteId(String takeSiteId) {
		set("take_site_id", takeSiteId);
	}

	public String getTakeSiteId() {
		return get("take_site_id");
	}

	public void setDueTime(java.util.Date dueTime) {
		set("due_time", dueTime);
	}

	public java.util.Date getDueTime() {
		return get("due_time");
	}

	public void setNum(Integer num) {
		set("num", num);
	}

	public Integer getNum() {
		return get("num");
	}

	public void setPrice(java.math.BigDecimal price) {
		set("price", price);
	}

	public java.math.BigDecimal getPrice() {
		return get("price");
	}

}
