package com.sf.jfinal.qs.model;

import com.sf.jfinal.qs.model.base.BaseCrmGoodsSiteselfOrder;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CrmGoodsSiteselfOrder extends BaseCrmGoodsSiteselfOrder<CrmGoodsSiteselfOrder> {
	public static final CrmGoodsSiteselfOrder dao = new CrmGoodsSiteselfOrder();
}
