package com.sf.jfinal.qs.model;

import com.sf.jfinal.qs.model.base.BaseCrmGoodsPlatformTransferOrder;

import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CrmGoodsPlatformTransferOrder extends BaseCrmGoodsPlatformTransferOrder<CrmGoodsPlatformTransferOrder> {
    public static final CrmGoodsPlatformTransferOrder dao = new CrmGoodsPlatformTransferOrder();

    public List<CrmGoodsPlatformTransferOrder> findByTradeNo(String tradeNo) {
        return dao.find("select * from crm_goods_platform_transfer_order where trade_no=?", tradeNo);
    }
}
