package com.sf.jfinal.qs.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUser<M extends BaseUser<M>> extends Model<M> implements IBean {

	public void setId(String id) {
		set("id", id);
	}

	public String getId() {
		return get("id");
	}

	public void setLoginName(String loginName) {
		set("login_name", loginName);
	}

	public String getLoginName() {
		return get("login_name");
	}

	public void setPassword(String password) {
		set("password", password);
	}

	public String getPassword() {
		return get("password");
	}

	public void setUserType(String userType) {
		set("user_type", userType);
	}

	public String getUserType() {
		return get("user_type");
	}

	public void setMobile(String mobile) {
		set("mobile", mobile);
	}

	public String getMobile() {
		return get("mobile");
	}

	public void setEmail(String email) {
		set("email", email);
	}

	public String getEmail() {
		return get("email");
	}

	public void setCreateBy(String createBy) {
		set("create_by", createBy);
	}

	public String getCreateBy() {
		return get("create_by");
	}

	public void setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
	}

	public java.util.Date getCreateDate() {
		return get("create_date");
	}

	public void setCreateType(String createType) {
		set("create_type", createType);
	}

	public String getCreateType() {
		return get("create_type");
	}

	public void setRemarks(String remarks) {
		set("remarks", remarks);
	}

	public String getRemarks() {
		return get("remarks");
	}

	public void setRegistrationId(String registrationId) {
		set("registration_id", registrationId);
	}

	public String getRegistrationId() {
		return get("registration_id");
	}

	public void setPushId(String pushId) {
		set("push_id", pushId);
	}

	public String getPushId() {
		return get("push_id");
	}

	public void setAppType(String appType) {
		set("app_type", appType);
	}

	public String getAppType() {
		return get("app_type");
	}

	public void setStatus(String status) {
		set("status", status);
	}

	public String getStatus() {
		return get("status");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}

	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

	public void setResetPwdToken(String resetPwdToken) {
		set("reset_pwd_token", resetPwdToken);
	}

	public String getResetPwdToken() {
		return get("reset_pwd_token");
	}

	public void setOpenid(String openid) {
		set("openid", openid);
	}

	public String getOpenid() {
		return get("openid");
	}

	public void setPermission(String permission) {
		set("permission", permission);
	}

	public String getPermission() {
		return get("permission");
	}

}
