package com.sf.jfinal.qs.model;

import com.sf.jfinal.qs.model.base.BaseCrmGoodsSiteself;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CrmGoodsSiteself extends BaseCrmGoodsSiteself<CrmGoodsSiteself> {
	public static final CrmGoodsSiteself dao = new CrmGoodsSiteself();
}
