package com.sf.jfinal.qs.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCrmGoodsSiteself<M extends BaseCrmGoodsSiteself<M>> extends Model<M> implements IBean {

	public void setId(String id) {
		set("id", id);
	}

	public String getId() {
		return get("id");
	}

	public void setSortNum(Integer sortNum) {
		set("sort_num", sortNum);
	}

	public Integer getSortNum() {
		return get("sort_num");
	}

	public void setNumber(String number) {
		set("number", number);
	}

	public String getNumber() {
		return get("number");
	}

	public void setName(String name) {
		set("name", name);
	}

	public String getName() {
		return get("name");
	}

	public void setBrand(String brand) {
		set("brand", brand);
	}

	public String getBrand() {
		return get("brand");
	}

	public void setModel(String model) {
		set("model", model);
	}

	public String getModel() {
		return get("model");
	}

	public void setCategory(String category) {
		set("category", category);
	}

	public String getCategory() {
		return get("category");
	}

	public void setLocation(String location) {
		set("location", location);
	}

	public String getLocation() {
		return get("location");
	}

	public void setUnit(String unit) {
		set("unit", unit);
	}

	public String getUnit() {
		return get("unit");
	}

	public void setUnitType(String unitType) {
		set("unit_type", unitType);
	}

	public String getUnitType() {
		return get("unit_type");
	}

	public void setDescription(String description) {
		set("description", description);
	}

	public String getDescription() {
		return get("description");
	}

	public void setIcon(String icon) {
		set("icon", icon);
	}

	public String getIcon() {
		return get("icon");
	}

	public void setImgs(String imgs) {
		set("imgs", imgs);
	}

	public String getImgs() {
		return get("imgs");
	}

	public void setSitePrice(java.math.BigDecimal sitePrice) {
		set("site_price", sitePrice);
	}

	public java.math.BigDecimal getSitePrice() {
		return get("site_price");
	}

	public void setEmployePrice(java.math.BigDecimal employePrice) {
		set("employe_price", employePrice);
	}

	public java.math.BigDecimal getEmployePrice() {
		return get("employe_price");
	}

	public void setCustomerPrice(java.math.BigDecimal customerPrice) {
		set("customer_price", customerPrice);
	}

	public java.math.BigDecimal getCustomerPrice() {
		return get("customer_price");
	}

	public void setRebateFlag(String rebateFlag) {
		set("rebate_flag", rebateFlag);
	}

	public String getRebateFlag() {
		return get("rebate_flag");
	}

	public void setRebatePrice(java.math.BigDecimal rebatePrice) {
		set("rebate_price", rebatePrice);
	}

	public java.math.BigDecimal getRebatePrice() {
		return get("rebate_price");
	}

	public void setDeductType(String deductType) {
		set("deduct_type", deductType);
	}

	public String getDeductType() {
		return get("deduct_type");
	}

	public void setNormalDeductAmount(java.math.BigDecimal normalDeductAmount) {
		set("normal_deduct_amount", normalDeductAmount);
	}

	public java.math.BigDecimal getNormalDeductAmount() {
		return get("normal_deduct_amount");
	}

	public void setRatioDeductRadix(String ratioDeductRadix) {
		set("ratio_deduct_radix", ratioDeductRadix);
	}

	public String getRatioDeductRadix() {
		return get("ratio_deduct_radix");
	}

	public void setRatioDeductVal(Integer ratioDeductVal) {
		set("ratio_deduct_val", ratioDeductVal);
	}

	public Integer getRatioDeductVal() {
		return get("ratio_deduct_val");
	}

	public void setSellFlag(String sellFlag) {
		set("sell_flag", sellFlag);
	}

	public String getSellFlag() {
		return get("sell_flag");
	}

	public void setSource(String source) {
		set("source", source);
	}

	public String getSource() {
		return get("source");
	}

	public void setStocks(java.math.BigDecimal stocks) {
		set("stocks", stocks);
	}

	public java.math.BigDecimal getStocks() {
		return get("stocks");
	}

	public void setSales(java.math.BigDecimal sales) {
		set("sales", sales);
	}

	public java.math.BigDecimal getSales() {
		return get("sales");
	}

	public void setReceives(java.math.BigDecimal receives) {
		set("receives", receives);
	}

	public java.math.BigDecimal getReceives() {
		return get("receives");
	}

	public void setSiteId(String siteId) {
		set("site_id", siteId);
	}

	public String getSiteId() {
		return get("site_id");
	}

	public void setStatus(String status) {
		set("status", status);
	}

	public String getStatus() {
		return get("status");
	}

}
